import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Good Vibes Hoodie',
    price: 49.99,
    image: '/goodvibespull.svg',
    category: 'Hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 756,
    badge: 'Best seller',
  },
  {
    id: '2',
    name: 'Good Music Good Vibes Shirt',
    price: 24.99,
    image: '/goodmusic.svg',
    category: 'T-Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 623,
    badge: 'New',
  },
  {
    id: '3',
    name: 'Have a Good Show T-Shirt',
    price: 24.99,
    image: '/haveagoodshow.svg',
    category: 'T-Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 534,
  },
  {
    id: '4',
    name: 'Festival Vibes Sticker',
    price: 0.5,
    image: '/festivalvibes.svg',
    category: 'Posters & Prints',
    sizes: [],
    rating: 3.8,
    reviews: 121,
  },
  {
    id: '5',
    name: 'Music Sticker',
    price: 1.0,
    image: '/music.svg',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.8,
    reviews: 831,
  },
  {
    id: '6',
    name: 'Good Vibes Sticker',
    price: 1.0,
    image: '/goodvibessticker.svg',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.2,
    reviews: 527,
  },
  {
    id: '7',
    name: 'Good Vibes Poster',
    price: 10.0,
    image: '/goodvibeschart.svg',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.2,
    reviews: 527,
  },
  {
    id: '8',
    name: 'Good Vibes Pin Set',
    price: 12.99,
    image: '/badges.svg',
    category: 'Accessories',
    sizes: [],
    rating: 4.5,
    reviews: 168,
    badge: '5% off',
  },
  {
    id: '9',
    name: 'Smiley Face Bucket Hat',
    price: 14.99,
    image: '/smileyhat.svg',
    category: 'Hats & Caps',
    sizes: ['S/M', 'L/XL'],
    rating: 4.5,
    reviews: 156,
  },
  {
    id: '10',
    name: 'Smiley Face Beanie Hat',
    price: 24.99,
    image: '/girlhat.svg',
    category: 'Hats & Caps',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 892,
  },
  {
    id: '11',
    name: 'Enjoy the Show Mug',
    price: 12.0,
    image: '/mug.svg',
    category: 'other',
    sizes: [],
    rating: 4.6,
    reviews: 234,
  },
  {
    id: '12',
    name: 'Rock On Lighter',
    price: 54.99,
    image: '/lighter.svg',
    category: 'other',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 1023,
  },
]

export const categories = [
  { name: 'All products', count: 24 },
  { name: 'T-Shirts', count: 16 },
  { name: 'Hoodies', count: 8 },
  { name: 'Accessories', count: 12 },
  { name: 'Hats & Caps', count: 6 },
  { name: 'Posters & Prints', count: 10 },
]
