import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Good Vibes Hoodie',
    description: 'Comfortable hoodie with colorful good vibes design',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    category: 'Hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 756,
    badge: 'Best seller',
  },
  {
    id: '2',
    name: 'Good Music Good Vibes Shirt',
    description: 'Bold graphic tee with good vibes message',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    category: 'T-Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 623,
    badge: 'New',
  },
  {
    id: '3',
    name: 'Have a Good Show T-Shirt',
    description: 'Rainbow text design perfect for concert lovers',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500',
    category: 'T-Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 534,
  },
  {
    id: '4',
    name: 'Festival Vibes Sticker',
    description: 'Colorful festival vibes sticker pack',
    price: 1.0,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500',
    category: 'Posters & Prints',
    sizes: [],
    rating: 3.8,
    reviews: 121,
  },
  {
    id: '5',
    name: 'Music Sticker',
    description: 'Retro music themed sticker collection',
    price: 1.0,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.8,
    reviews: 831,
  },
  {
    id: '6',
    name: 'Good Vibes Sticker',
    description: 'Holographic good vibes sticker set',
    price: 1.0,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.2,
    reviews: 527,
  },
  {
    id: '7',
    name: 'Good Vibes Poster',
    description: 'Vintage concert poster with lineup',
    price: 10.0,
    image: 'https://images.unsplash.com/photo-1594122230689-45899d9e6f69?w=500',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.2,
    reviews: 527,
  },
  {
    id: '8',
    name: 'Good Vibes Pin Set',
    description: 'Colorful enamel pin collection',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=500',
    category: 'Accessories',
    sizes: [],
    rating: 4.5,
    reviews: 168,
    badge: '5% off',
  },
  {
    id: '9',
    name: 'Smiley Face Bucket Hat',
    description: 'Fun yellow smiley face bucket hat',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500',
    category: 'Hats & Caps',
    sizes: ['S/M', 'L/XL'],
    rating: 4.5,
    reviews: 156,
  },
  {
    id: '10',
    name: 'Rock Festival Tee',
    description: 'Classic rock festival graphic tee',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
    category: 'T-Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 892,
  },
  {
    id: '11',
    name: 'Concert Memories Poster',
    description: 'Vintage style concert poster',
    price: 12.0,
    image: 'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=500',
    category: 'Posters & Prints',
    sizes: [],
    rating: 4.6,
    reviews: 234,
  },
  {
    id: '12',
    name: 'Artist Tour Hoodie',
    description: 'Limited edition tour hoodie',
    price: 54.99,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    category: 'Hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 1023,
    badge: 'Best seller',
  },
]

export const categories = [
  { name: 'All products', count: 24 },
  { name: 'T-Shirts', count: 16 },
  { name: 'Hoodies', count: 8 },
  { name: 'Accessories', count: 12 },
  { name: 'Hats & Caps', count: 6 },
  { name: 'Posters & Prints', count: 10 },
]
